SI507_Final_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    path('data/', include('data.urls', namespace='data')),
    path('admin/', admin.site.urls),
]

data/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
app_name = 'data'

urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    path('reddit', views.RedditListView.as_view(), name='reddit'),
    path('comment/<str:subid>', views.RedditCommentView.as_view(), name='comments'),
    path('twitter', views.TwitterListView.as_view(), name='twitter'),
]

data/models.py
from django.db import models

# Create your models here.

SI507_Final_Project/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.html import escape
from django.views import View
from django.shortcuts import render, redirect



class HomeView(View):
    def get(self, request):
        return redirect(reverse_lazy("data:all"))

data/views.py
from django.views import View
from django.shortcuts import render, redirect
import sys
import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = BASE_DIR
sys.path.append(os.path.join(ROOT_DIR, 'analysis'))
import get_reddit
import get_twitter
import process_reddit
import pandas as pd


class HomeView(View):
    def get(self, request):
        reddit = get_reddit.make_reddit_request()
        submission = get_reddit.get_subreddit_submissions(reddit, "news", 100)
        submission_df = pd.DataFrame(submission,
                                     columns=['SUBID', 'URL', 'TITLE', 'SUBREDDIT', 'SCORE', 'SELFTEXT', 'NUMCOUNTS',
                                              'CREATE_TIME'])
        src_reddit = process_reddit.word_cloud(submission_df, 'TITLE', "reddit word cloud: news")
        twitter = get_twitter.get_twitter("news lang:en - is: retweet", "#world news", 100)
        twitter_df = pd.DataFrame(twitter, columns=["content"])
        src_twitter = process_reddit.word_cloud(twitter_df, 'content', "twitter word cloud: world news")
        return render(request, 'data/main.html', {"src_reddit": src_reddit, "src_twitter": src_twitter})


class RedditListView(View):
    def get(self, request):
        reddit = get_reddit.make_reddit_request()
        submission = get_reddit.get_subreddit_submissions(reddit, "coronavirus", 100)
        submission_df = pd.DataFrame(submission,
                                     columns=['SUBID', 'URL', 'TITLE', 'SUBREDDIT', 'SCORE', 'SELFTEXT', 'NUMCOUNTS',
                                              'CREATE_TIME'])
        src = process_reddit.auto()
        cntx = {
            'src': src,
        }
        print(src)
        return render(request, 'data/reddit.html', cntx)

    def post(self,request):
        subreddit = request.POST.get("subreddit")
        date1 = request.POST.get("datepicker")
        date2 = request.POST.get("datepicker2")
        order = request.POST.get("order")
        limit = request.POST.get("limit")
        submission_time = date1+","+date2
        reddit_list = process_reddit.select_submission(subreddit, submission_time, order, limit)
        reddit_list = [(x[0],x[2]) for x in reddit_list]
        cntx = {
            "reddit_list": reddit_list,
        }
        return render(request, 'data/reddit.html', cntx)


class RedditCommentView(View):
    def get(self, request, subid):
        return render(request, 'data/reddit_comment.html', {"subid": subid})

    def post(self, request, subid):
        reddit = get_reddit.make_reddit_request()
        limit = int(request.POST.get("limit"))
        comments = get_reddit.get_submission_comment(reddit, subid, limit)
        comments_list = [x[1] for x in comments]
        cntx = {
            'comments_list': comments_list,
            'subid': subid,
        }
        return render(request, 'data/reddit_comment.html', cntx)


class TwitterListView(View):
    def get(self, request):
        return render(request, 'data/twitter.html')

    def post(self,request):
        value = request.POST.get("value")
        tag = request.POST.get("tag")
        limit = int(request.POST.get("limit"))
        print((value,tag,limit))
        twitter_list = get_twitter.get_twitter(value, tag, limit)
        print(twitter_list)
        return render(request, 'data/twitter.html', {'twitter_list': twitter_list})

data/templates/data/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        <li><a href="{% url "data:reddit" %}">reddit</a></li>
        <li><a href="{% url "data:twitter" %}">twitter</a></li>
    </ul>
    <div class="data_distribution">
        <div class="show_img" style="width:500px; height:250px;">
            <img src="{{ src_reddit }}" width="100%" height="100%" alt="word cloud"/>
        </div><br>
        <div class="show_img" style="width:500px; height:250px;">
            <img src="{{ src_twitter }}" width="100%" height="100%" alt="word cloud"/>
        </div>
    </div>
</body>
</html>

data/templates/data/reddit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reddit</title>
</head>
<style>
    a:visited, a:hover, a:active {
    color:#000000;
    text-decoration:none;
    }
</style>
<body>
    <h3>Reddit sentimental score</h3>
    <div class="data_distribution">
        <div class="show_img">
            <img src="{{ src }}" alt="exploratory data analysis"/>
        </div>
{#        <p>{{ score }}</p>#}
    </div>
<form action="{% url 'data:reddit' %}", method="post">
    {% csrf_token %}
    <div>
    <p>
        Enter a subreddit name, e.g. "news" <input name="subreddit" type="text"/><br/>
        Enter a period of time, start from 2021/4/22 <input type="date" name="datepicker" class='form-control' id="startd"  value="2021-4-22" required/> &nbsp;&nbsp;
        end <input type="date" name="datepicker2" class='form-control' id="endd"required  value="2021-4-23" /> <br>
        Order by?
        <select name="order">
            <option value="NUMCOMMENTS">num of comments</option>
            <option value="SCORE">score</option>
            <option value="none">none</option>
        </select>
        Enter the number of submissions you want to return <input style="width:30px;" name="limit" type="text"
                                                                  maxlength="4" oninput = "value=value.replace(/[^\d]/g,'')"/><br/>
        <input type="submit" name="dopost" value="submit" />
    </p>
    </div>
</form>

    <p>{% if reddit_list %}
        <ol>
        {% for subid, title in reddit_list %}
            <li><p style="line-height:5px;"><a href="{% url "data:comments" subid%}">{{ title }}</a></p></li>
        {% endfor %}
        </ol>
        </div>
    {% endif %}
    </p>
<a href="{% url 'data:all' %}">Go back to home page.</a>
</body>
</html>

data/templates/data/reddit_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'data:comments' subid %}", method="post">
    {% csrf_token %}
    <div>
    <p>
    Enter the number of comments you want to return <input style="width:30px;" name="limit" type="text"
                                                           maxlength="4" oninput = "value=value.replace(/[^\d]/g,'')"/><br/>
        <p>Please refresh the page if you see the primary keys.</p>
    <input type="submit" name="dopost" value="submit" />
    </p>
    </div>
</form>
    {% if comments_list %}
    <ol>
        {% for comment in comments_list %}
        <li>{{ comment }}</li>
        {% endfor %}
    </ol>
    {% endif %}
<a href="{% url 'data:reddit' %}">Go back to reddit submission.</a>
</body>
</html>

data/templates/data/twitter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Twitter</title>
</head>

<body>
 <h3>Twitter filter</h3>
<form action="{% url 'data:twitter' %}", method="post">
    {% csrf_token %}
    <div>
    <p>
        <p> ( e.g. value: news lang:en - is: retweet, tag: #world news )<br>
        <a href="https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/build-a-rule">How to build a rule for twitter</a></p>
        Enter a value <input name="value" type="text"/><br/>
        Enter a tag <input name="tag" type="text"/><br/>
        Enter the number of twitters you want to return <input style="width:30px;" name="limit" type="text"
                                                                  maxlength="4" oninput = "value=value.replace(/[^\d]/g,'')"/><br/>
        <input type="submit" name="dopost" value="submit" />
    </p>
    </div>
</form>
    <p>{% if twitter_list %}
        <ol>
        {% for twitter in twitter_list %}
            <li><p style="line-height:20px;">{{ twitter }}</p></li>
        {% endfor %}
        </ol>
        </div>
    {% endif %}
    </p>
<a href="{% url 'data:all' %}">Go back to home page.</a>
</body>
</html>